# Generated by Django 5.1.4 on 2024-12-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('White', 'White'), ('Black', 'Black'), ('CAFE', 'Cafe')], default='Black', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', '')], default='M', max_length=2),
        ),
    ]
