# Generated by Django 5.1.4 on 2024-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_color_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pants', 'Pants'), ('jackets', 'Jackets'), ('tops', 'Tops'), ('hoodies', 'Hoodies'), ('dress', 'Dress')], max_length=40),
        ),
    ]
